#!/bin/bash

if [ $# -eq 0 ]; then
    echo "No arguments provided. Please provide an argument."
    exit 1
fi

execute_command() {
    case $1 in
        run)
            ./mvnw spring-boot:run
            ;;
        clean)
            ./mvnw clean
            ;;
        install)
            ./mvnw install
            ;;
        compile)
            ./mvnw native:compile -Pnative
            ;;
        build-docker)
            docker build -t fretquiz .
            ;;
        run-docker)
            docker run -it -p 8080:8080 --rm fretquiz
            ;;
        *)
            echo "Valid arguments: 'run', 'clean', 'install', 'compile', 'build-docker', 'run-docker'"
            exit 1
            ;;
    esac
}

execute_command "$1"
