version: '3.8'

services:
  app:
    build: .
    ports:
      - "8081:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/fretquiz
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    depends_on:
      - db

  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: fretquiz
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"  # Map port 5433 on the host to 5432 in the container
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
